# Generated by Django 5.2.2 on 2025-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'student',
                'ordering': ['order'],
            },
        ),
    ]
