# Generated by Django 5.2.2 on 2025-07-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('students', models.ManyToManyField(related_name='classes', to='students.student')),
            ],
            options={
                'db_table': 'class',
            },
        ),
    ]
