# Generated by Django 5.2.2 on 2025-07-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentorder',
            table='studentorder',
        ),
    ]
